version: '3'
services:
  postgre:
    container_name: db
    image: postgres:latest
    restart: always
    networks:
      - bridge
    volumes:
     - ./data/postgre:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

  backend:
    container_name: backend
    build: ./backend
    restart: always
    networks:
      - bridge
    volumes:
      -  ./backend:/app
      -  /usr/src/app/node_modules
      - ./backend/media/:/media/
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgre

  frontend:
    container_name: frontend
    build: ./frontend
    #restart: always
    networks:
      - bridge
    volumes:
      - ./frontend:/usr/src/app/src
      #- ./frontend:/usr/share/nginx/html
      -  /usr/src/app/node_modules
    env_file:
      - frontend/.env
    ports:
      -  "5174:5174"
    depends_on:
      - backend
    #command: /bin/sh -c "while sleep 1000; do :; done"

#  matchmaking:
#    container_name: matchmaking
#    build: ./matchmaking/docker
#    volumes:
#      - ./matchmaking/src:/app/src
#      - ./matchmaking/Cargo.toml:/app/Cargo.toml
#    networks:
#      - bridge
#    command: cargo run
#    ports:
#      - "5555:5555"

networks:
  bridge:
    driver: bridge

#docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' backend